### ISSUE TITLE
Update meta mod info

### ISSUE THREAD

**Issue by 2zqa** [telvarost/AnnoyanceFix-StationAPI#12]
Any links to the Babric version should be replaced with StationAPI, descriptions should be actually descriptive instead of pointing to the modloader edition, missing logo should be fixed (readme to be fixed in separate issue, see #6), display name shouldn't show StationAPI (it is immediately obvious the user is already using StationAPI)

Perhaps more things?

**Comment by 2zqa** [comment]
Should the logo have a StationAPI label to indicate this is the StationAPI edition? Babric edition has this but Modloader edition doesn't.

**Comment by telvarost** [comment]
> Should the logo have a StationAPI label to indicate this is the StationAPI edition? Babric edition has this but Modloader edition doesn't.

I suppose so, just to differentiate it from the babric version. The babric version only has a label to differentiate it from the modloader version, so this is sort of the same thing.
