### ISSUE TITLE
5% durability buff when repairing items to match modern minecraft

### ISSUE THREAD

**Issue by telvarost** [telvarost/AnnoyanceFix-StationAPI#21]
See Minecraft's Documentation on Item Repair:
https://minecraft.fandom.com/wiki/Item_repair

This issue was brought to our attention by KydZombie.
See the StationAPI version's comment section on Modification-Station for his thoughts.

**Comment by telvarost** [comment]
Completed-ish. I've got a lot of questions about implementation and design on this one.

**Comment by telvarost** [comment]
Also, should we let players repair tools? Currently we only allow armor repair.

**Comment by 2zqa** [comment]
If we allow armor we might as well do tools as well. Would make sense.
