### ISSUE TITLE
Should we also release to modrinth?

### ISSUE THREAD

**Issue by telvarost** [telvarost/AnnoyanceFix-StationAPI#33]

**Comment by telvarost** [comment]
I see the modrinth release ticket was closed. Does this mean that our GitHub release strategy was deemed to be good enough and no modrinth release should be made?

https://github.com/telvarost/AnnoyanceFix-StationAPI/issues/9

**Comment by matthewperiut** [comment]
I say yes, put it on modrinth. I should probably start putting my b1.7.3 mods on modrinth too, but since minediver is starting to, we probably should too

**Comment by 2zqa** [comment]
I agree. I must've not been thinking straight when closing #9. I'll open that issue and close this one.
