### ISSUE TITLE
Define dependencies and optional dependencies

### ISSUE THREAD

**Issue by 2zqa** [telvarost/AnnoyanceFix-StationAPI#38]
https://github.com/Kir-Antipov/mc-publish#dependencies

Defining these will make it more clear on the Modrinth page which mods should be used, like the mod list for the mod settings.

For example, the BetterNetherBeta `fabric.mod.json`: https://github.com/paulevsGitch/BetterNetherBeta/blob/master/src/main/resources/fabric.mod.json lists the stationloader version.

**Comment by telvarost** [comment]
Completed, we now depend on GCAPI3, StationAPI, and recommend ModMenu
