### ISSUE TITLE
Ability to somehow collect cobwebs perhaps shears like modern minecraft

### ISSUE THREAD

**Issue by telvarost** [telvarost/AnnoyanceFix-StationAPI#8]

**Comment by telvarost** [comment]
Completed

**Comment by 2zqa** [comment]
I believe we mentioned that cobwebs don't spawn in b1.7.3. I therefore don't think we need this feature. It would be the responsibility of the mod that adds cobwebs to this version of Minecraft to implement this fix IMO. Feel free to re-open if you disagree.

**Comment by 2zqa** [comment]
Re-opened because cobwebs are part of vanilla Minecraft, even though you cannot legally obtain it
